### ISSUE TITLE
是不是少了引号？

### ISSUE THREAD

**Issue by Nutlee** [futuweb/gulp-rev-hash3#1]
index.js 中172行

```
 newLineSymbol = “\r;
```

使用时这里一直报错。

**Comment by AlanZhang001** [comment]
你好，谢谢你的反馈，插件发布过程中出现了问题，已修正；请下载最新的版本1.0.7；对于问题版本1.0.6已做unpublish处理；
地址：https://www.npmjs.com/package/gulp-rev-hash3
