### ISSUE TITLE
请问可否加入相对路径支持？ 谢谢

### ISSUE THREAD

**Issue by Nutlee** [futuweb/gulp-rev-hash3#2]
您好，拿本项目试过了直接运行是 ok 的，但如果 script、link 标签 src 、href 中使用相对路径，运行会报错，考虑到实际不同项目的复杂情况，不知道是我的姿势不对还是怎样，还请指点一二，谢谢。

**Comment by Nutlee** [comment]
自己解决了 ，期待作者更好的方案 😄

**Comment by AlanZhang001** [comment]
@Nutlee 相对路径的支持已经处理。并没有采用你PR的方案。解决方案：
1. 获取到当前处理的html的路径，及静态资源的相对路径
2. 做join操作，即可拿到相对路径的静态资源的绝对路径，再进行计算hash处理。

前期项目中几乎不采用相对路径的做法，因此未提供对相对路径的全支持。

最近npm 见 https://www.npmjs.com/package/gulp-rev-hash3

同时谢谢你提出的思路！

**Comment by Nutlee** [comment]
@AlanZhang001 
不好意思，恕我冒昧，您可能没看清我的意思，您的相对路径支持并没有完全支持 ”../“ 这种相对路径，我的提交只有两处 `join` 改为 `resolve`，test 中的目录方案只是为了单纯演示，就是说以之前的目录方案是没问题的，如果用户使用我这种目录结构也没问题，只是在 CDN 的路径支持上仍有改进空间。

目前接触过的项目中相对路径也很多，可能小公司的原因😄 ，不太明白您所说

> 前期项目中几乎不采用相对路径的做法

个人认为这样修改向前兼容且给用户提供了更多可能，感谢您的回复。

**Comment by AlanZhang001** [comment]
@Nutlee  可以说下 你说的没有完全支持'../'的场景吗？如果存在问题，我继续改进
继续讨论，没啥冒昧的，这块我也接触不久。。。

 

目录结构往往不能确定，特别是多人开发的时候，所以我司基本上是统一通过cdn去处理这个问题，静态资源统一以cdn为根目录。

相对路径静态资源在文件目录中真实路径，合理的方式是先找到html的绝对路径，然后再去以html为基准，找到这类静态资源的绝对路径。
仅仅通过resovle是无法找到的。例如下图，不同html中引用的js文件一样，相对路径不一样，但是resolve的结果肯定不一样
![image](https://cloud.githubusercontent.com/assets/9763641/20997372/d5ddb91c-bd3f-11e6-91e2-5221e230ff34.png)


另外，对于你提供的目录结构，如果在test目录下新增一个html目录，里面的html文件在处理时将会报错，下面是我clone你的方案修改了gulpfile，增加了html。

![image](https://cloud.githubusercontent.com/assets/9763641/20996826/6d5ea382-bd3b-11e6-9579-d71fcb879bc7.png)
![image](https://cloud.githubusercontent.com/assets/9763641/20996845/931b9f44-bd3b-11e6-818d-cce5a33eeb82.png)
![image](https://cloud.githubusercontent.com/assets/9763641/20997027/d282ecae-bd3c-11e6-849e-628e7dde558e.png)

我在仓库https://github.com/futuweb/gulp-rev-hash3中加了几个html，你可以看下

**Comment by Nutlee** [comment]
@AlanZhang001 啊 不好意思我没看到你的更新以为还是之前的版本，恩 您这个思路更通用一点，更好。我想简单了只能针对写死 test/html 放 html 的情况。

另外，似乎如下代码中均使用 `path.join(htmlpath, filepath)` 也是没问题
，这样 assets 的设置就没意义了

```
 return isRelativePath(filepath) ? path.join(htmlpath, filepath) :
 path.join(options.assetsDir, filepath);
```

还有请教一下如果使用CDN，同时又使用相对路径这种多文件夹的情况下，例如 js 在 HTML 中可以这么写

```
<link rel="stylesheet" href="//cdn.xxxx.com/main.min2.css">
```

gulpfile 中

```
      remotePath:[{
          domain:"cdn.xxxx.com",
          path:"test/js"
      }]
```
但如果此时 css 也使用 CDN 但 remotePath 中 path 已经写了 test/js 怎么再配置 test/css ？ 请教一下，谢谢

**Comment by AlanZhang001** [comment]
@Nutlee assetsDir是否有意义，就看你怎么定义相对路径了，xxx.css 这里，我不认为他是一个相对路径，这个时候就当做assertDir目录下的问题来处理。

另外你的问题，
remotePath可以配置多组域名，如果你的css和js不在同一个cdn下，那多配置一个cdn就好了

配置
![image](https://cloud.githubusercontent.com/assets/9763641/21003617/5856c556-bd67-11e6-98e5-a9e1048ab880.png)

使用
![image](https://cloud.githubusercontent.com/assets/9763641/21003605/4fba9d50-bd67-11e6-92b0-f3770f5a70b9.png)

如果你想一个cdn域名对应多个路径，这个是做不到的。

**Comment by Nutlee** [comment]
@AlanZhang001   
好的 问题都解决了 ，再次感谢 可以关贴了😄
